store:
    image: postgres:latest 
    volumes:
        - /var/lib/postgresql/data
    command: "true"

postgresdb:
    image: postgres:latest
    ports:
        - "5432" 
    volumes_from:
        - store 
    environment:
        - POSTGRES_PASSWORD=cumbaya
       

go:
    build: .    
    links:
        - postgresdb
    ports:
        - "8080:8080"