store:
    image: postgres:latest 
    volumes:
        - /var/lib/postgresql/data
    command: "true"

postgresdb:
    image: postgres:latest
    ports:
        - "5432:5432" 
    volumes_from:
        - store 
    environment:
        - POSTGRES_PASSWORD=cumbaya
        - POSTGRES_DB=truesize  

postgresdbtest:
    image: postgres:latest
    ports:
        - "5433:5432" 
    volumes_from:
        - store 
    environment:
        - POSTGRES_PASSWORD=cumbaya
        - POSTGRES_DB=truesize_test 

go:
    build: .
    links:
        - postgresdb
    ports:
        - "8080:8080"

admin:
    image: adminer
    restart: always
    links: 
        - postgresdb
        - postgresdbtest
    ports:
        - 8081:8080