postgresdb:
    image: postgres:latest
    ports:
        - "5432:5432" 
    environment:
        - POSTGRES_PASSWORD=cumbaya
        - POSTGRES_DB=truesize  

admin:
    image: adminer
    restart: always
    links: 
        - postgresdb
    ports:
        - 8081:8080

go:
    build: .
    links:
        - postgresdb
    ports:
        - "8080:8080"