store:
    image: postgres:latest 
    volumes:
        - /var/lib/postgresql/data
    command: "true"

postgresdb:
    build: ./docker/postgres
    ports:
        - "5432" 
    volumes_from:
        - store 
    environment:
        - POSTGRES_PASSWORD=cumbaya      

go:
    build: ./docker/golang   
    links:
        - postgresdb
    ports:
        - "8080:8080"

admin:
    image: adminer
    restart: always
    links: 
        - postgresdb
    ports:
        - 8081:8080